version: '3.8'

services:
  # 1. MariaDB
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tnut_food
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # 2. PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-pma
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  # 3. Node-RED
  nodered:
    image: nodered/node-red:latest
    container_name: my-nodered
    environment:
      - NODE_RED_HTTP_ROOT=/nodered/
      - NODE_RED_HTTP_ADMIN_ROOT=/nodered/
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data 

  # 4. InfluxDB
  influxdb:
    image: influxdb:1.8
    container_name: my-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  # 5. Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: my-grafana
    environment:
      - GF_SERVER_DOMAIN=nguyenmanhhieu.com
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_INSTALL_PLUGINS=
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  # 6. Nginx
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/var/www/html/images
    depends_on:
      - nodered
      - grafana

volumes:
  mariadb_data:
  nodered_data:
  influxdb_data:
  grafana_data: